version: '3'

services:
  app:
    build: .
    working_dir: "${PWD}"
    command: "true"
    ports:
      - "4444:4444" # nrepl
      - "4445:4445" # http
    environment:
      - "GITLIBS=${PWD}/.gitlibs"
    volumes:
      - ".:${PWD}:cached"
