version: '3'

services:
  app:
    build: .
    working_dir: /usr/src/app
    command: lein repl :headless :host "0.0.0.0" :port 4100
    ports:
      - "4100:4100"
      - "4101:4101"
    volumes:
      - repository:/root/.m2
      - .:/usr/src/app
      - ~/.lein:/root/.lein:ro
volumes:
  repository:
